/**
 * Where an ILIAS installation keeps the things Uni Pilot wants to read.
 *
 * Two of these paths move between releases and one differs per university, so
 * building them by hand at each call site is how a connector quietly breaks on
 * the next upgrade.
 */

/**
 * ILIAS 10 moved the web root into `public/`, which shortened the SOAP path.
 * Everything before that serves it from `webservice/`.
 *
 * Source: the `ilSoapWsdlPathUpdateStep` migration rewrites the stored WSDL
 * path from `/webservice/` to `/public/` when an installation updates to 10.
 */
export type IliasLayout = 'legacy' | 'public-root';

/** ILIAS releases the connector has been reasoned about. */
export const OLDEST_SUPPORTED_RELEASE = 8;
export const FIRST_PUBLIC_ROOT_RELEASE = 10;

/**
 * Reads the major release out of whatever version string an installation
 * reports — `9.23`, `10.11 2026-09-03`, `8` — and returns null for anything
 * that is not a version at all.
 */
export function majorRelease(version: string): number | null {
  const major = /^\s*(\d+)/.exec(version)?.[1];
  if (major === undefined) return null;
  const parsed = Number(major);
  return Number.isFinite(parsed) ? parsed : null;
}

export function layoutForRelease(release: number): IliasLayout {
  return release >= FIRST_PUBLIC_ROOT_RELEASE ? 'public-root' : 'legacy';
}

/** Strips a trailing slash and any page a user pasted along with the address. */
export function normaliseBaseUrl(input: string): string {
  const trimmed = input.trim();
  if (!trimmed) return '';
  const withScheme = /^https?:\/\//i.test(trimmed) ? trimmed : `https://${trimmed}`;
  let url: URL;
  try {
    url = new URL(withScheme);
  } catch {
    return '';
  }
  // People paste `…/ilias.php?baseClass=…`; the directory holding it is the root.
  const directory = url.pathname.replace(/\/[^/]*$/, '');
  return `${url.origin}${directory}`.replace(/\/$/, '');
}

export function soapEndpoint(baseUrl: string, layout: IliasLayout): string {
  const base = normaliseBaseUrl(baseUrl);
  return layout === 'public-root'
    ? `${base}/soap/server.php`
    : `${base}/webservice/soap/server.php`;
}

/**
 * Both candidates, newest first. Used once when connecting, so the connector
 * can find the endpoint without being told the release up front.
 */
export function soapEndpointCandidates(baseUrl: string): readonly string[] {
  return [soapEndpoint(baseUrl, 'public-root'), soapEndpoint(baseUrl, 'legacy')];
}

/**
 * The per-user iCal subscription. The token is generated by the student inside
 * ILIAS and stands in for their password, which is why this path works without
 * Uni Pilot ever holding a credential.
 */
export function calendarSubscriptionUrl(baseUrl: string, clientId: string, token: string): string {
  const query = new URLSearchParams({ client_id: clientId, token });
  return `${normaliseBaseUrl(baseUrl)}/calendar.php?${query.toString()}`;
}

/**
 * The private news feed. Authenticated with HTTP Basic against a *separate*
 * feed password that the student sets in their ILIAS profile — not their
 * university password, which is the entire reason this path is acceptable.
 */
export function privateNewsFeedUrl(
  baseUrl: string,
  clientId: string,
  userId: string,
  hash: string,
): string {
  const query = new URLSearchParams({ client_id: clientId, user_id: userId, hash });
  return `${normaliseBaseUrl(baseUrl)}/privfeed.php?${query.toString()}`;
}

/** Deep link to any repository object, for the "open in ILIAS" fallback. */
export function objectUrl(baseUrl: string, refId: string, type = 'crs'): string {
  return `${normaliseBaseUrl(baseUrl)}/goto.php?target=${type}_${refId}`;
}
