import type { MermaidConfig } from 'mermaid';

export const DIAGRAM_FONT = 'JetBrains Mono, ui-monospace, monospace';

/** A compact, flat diagram palette that sits on the note's own paper. */
export function diagramConfig(dark: boolean): MermaidConfig {
  const colors = dark
    ? {
        text: '#d7e0ec',
        line: '#8090a4',
        blue: '#243347',
        blueBorder: '#576f91',
        blueText: '#c3d7f5',
        green: '#233b32',
        greenBorder: '#4c7965',
        greenText: '#b7e1cc',
        violet: '#343047',
        violetBorder: '#746789',
        violetText: '#dccdf2',
        amber: '#423727',
        amberBorder: '#8e7650',
        amberText: '#ecd2a7',
        background: '#1d232a',
        faint: '#29303a',
        mutedBorder: '#4b5665',
      }
    : {
        text: '#334155',
        line: '#8796a9',
        blue: '#eff5ff',
        blueBorder: '#a9c0e2',
        blueText: '#355b91',
        green: '#edf7f1',
        greenBorder: '#accfbb',
        greenText: '#356b53',
        violet: '#f4f0fb',
        violetBorder: '#c9b9df',
        violetText: '#6b528b',
        amber: '#fff6e9',
        amberBorder: '#dfc49b',
        amberText: '#88602f',
        background: '#ffffff',
        faint: '#f8fafc',
        mutedBorder: '#d2dae4',
      };
  return {
    theme: 'base',
    look: 'classic',
    fontFamily: DIAGRAM_FONT,
    fontSize: 13,
    themeVariables: {
      darkMode: dark,
      background: colors.background,
      fontFamily: DIAGRAM_FONT,
      fontSize: '13px',
      primaryColor: colors.blue,
      primaryBorderColor: colors.blueBorder,
      primaryTextColor: colors.blueText,
      secondaryColor: colors.green,
      secondaryBorderColor: colors.greenBorder,
      secondaryTextColor: colors.greenText,
      tertiaryColor: colors.violet,
      tertiaryBorderColor: colors.violetBorder,
      tertiaryTextColor: colors.violetText,
      textColor: colors.text,
      lineColor: colors.line,
      edgeLabelBackground: colors.background,
      clusterBkg: colors.faint,
      clusterBorder: colors.mutedBorder,
      titleColor: colors.text,
      actorBkg: colors.blue,
      actorBorder: colors.blueBorder,
      actorTextColor: colors.blueText,
      actorLineColor: colors.mutedBorder,
      signalColor: colors.line,
      signalTextColor: colors.text,
      labelBoxBkgColor: colors.faint,
      labelBoxBorderColor: colors.mutedBorder,
      labelTextColor: colors.text,
      noteBkgColor: colors.amber,
      noteBorderColor: colors.amberBorder,
      noteTextColor: colors.amberText,
      activationBkgColor: colors.green,
      activationBorderColor: colors.greenBorder,
      cScale0: colors.blue,
      cScale1: colors.green,
      cScale2: colors.violet,
      cScale3: colors.amber,
      cScale4: colors.blue,
      cScale5: colors.green,
      cScaleLabel0: colors.blueText,
      cScaleLabel1: colors.greenText,
      cScaleLabel2: colors.violetText,
      cScaleLabel3: colors.amberText,
      cScaleLabel4: colors.blueText,
      cScaleLabel5: colors.greenText,
    },
    // Only standard strokes are refined; authored colors and thick edges still win.
    themeCSS: `
      .edge-thickness-normal, .messageLine0, .messageLine1 { stroke-width: 1.1px; }
      .actor-line { stroke-width: 0.75px; }
      .mindmap-node circle + .label text, .mindmap-node ellipse + .label text { text-anchor: middle; }
      .mindmap-node.section-root > .label-container { fill: ${colors.blue}; stroke: ${colors.blueBorder}; stroke-width: 1px; }
      .edge[class*="section-edge-"] { stroke: ${colors.line}; }
    `,
    flowchart: {
      diagramPadding: 8,
      padding: 10,
      minNodeWidth: 0,
      nodeSpacing: 32,
      rankSpacing: 44,
      curve: 'basis',
    },
    sequence: {
      diagramMarginX: 8,
      diagramMarginY: 12,
      actorMargin: 40,
      width: 88,
      height: 34,
      messageMargin: 32,
      mirrorActors: false,
      actorFontFamily: DIAGRAM_FONT,
      actorFontSize: 13,
      noteFontFamily: DIAGRAM_FONT,
      noteFontSize: 12,
      messageFontFamily: DIAGRAM_FONT,
      messageFontSize: 12,
    },
    state: { padding: 10, nodeSpacing: 32, rankSpacing: 42 },
    mindmap: { padding: 10 },
  };
}
