import type { ReactNode } from 'react';
import {
  Heading1,
  Heading2,
  Heading3,
  ImagePlus,
  List,
  ListChecks,
  ListOrdered,
  Minus,
  Pilcrow,
  Quote,
  SquareCode,
  Table,
  StickyNote,
  Square,
  Circle,
  Diamond,
  ArrowRight,
  Network,
  Columns2,
  NotebookTabs,
  LayoutDashboard,
  GitBranch,
  Sigma,
  Radical,
  ListCollapse,
  Superscript,
} from 'lucide-react';
import type { SlashCommand } from '@/features/documents/lib/blockTypes';

/** One icon per `/` command, shared with the block options' “Turn into” list. */
export const SLASH_ICONS: Record<SlashCommand['id'], ReactNode> = {
  paragraph: <Pilcrow size={15} />,
  heading1: <Heading1 size={15} />,
  heading2: <Heading2 size={15} />,
  heading3: <Heading3 size={15} />,
  bulletList: <List size={15} />,
  orderedList: <ListOrdered size={15} />,
  taskList: <ListChecks size={15} />,
  blockquote: <Quote size={15} />,
  codeBlock: <SquareCode size={15} />,
  formula: <Sigma size={15} />,
  inlineFormula: <Radical size={15} />,
  toggle: <ListCollapse size={15} />,
  footnote: <Superscript size={15} />,
  mermaid: <Network size={15} />,
  divider: <Minus size={15} />,
  table: <Table size={15} />,
  image: <ImagePlus size={15} />,
  'sticky-yellow': <StickyNote size={15} />,
  'sticky-peach': <StickyNote size={15} />,
  'sticky-mint': <StickyNote size={15} />,
  'sticky-blue': <StickyNote size={15} />,
  rectangle: <Square size={15} />,
  ellipse: <Circle size={15} />,
  diamond: <Diamond size={15} />,
  arrow: <ArrowRight size={15} />,
  'study-card': <StickyNote size={15} />,
  flow: <GitBranch size={15} />,
  compare: <Columns2 size={15} />,
  cornell: <NotebookTabs size={15} />,
  'study-board': <LayoutDashboard size={15} />,
  'mind-map': <Network size={15} />,
};
